### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by myssun0325**
I've added how to install RVB xcode's template :)

### CODE REVIEW

**Comment by wlsdms0122** [comment]
Please rewrite formatted style like this. 😂

```
# 📌 Reference
> Add any references to help understand this pull request.


# 🔥 Cause
> If there is a reason, write why the code changes was occurred.


# 📄 Changes
> Write what is changed.
> You can write more detail informations using MD syntax.


# 🚧 Testing
> Write how to test and results of changes using screenshots, gifs, any others.

```

**Comment by myssun0325** [comment]
Please add PR Template. 🤖

**Comment by wlsdms0122** [comment]
Added template. reference #5

**Comment by myssun0325** [comment]
Good 👍

**Pull request closed without merging**
